backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/images
public_folder: /images
publish_mode: editorial_workflow

collections:
  - name: "pages"
    label: "Pages"
    description: "Hi Joe"
    files:
      - label: "Bio"
        name: "bio"
        file: "content/bio.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Watch"
        name: "watch"
        file: "content/watch.md"
        fields:
          - label: "Youtube URLs"
            name: "youtubeurls"
            widget: list
            fields:
              - { label: "URL", name: "url", widget: "string" }
      - label: "Listen"
        name: "listen"
        file: "content/listen.md"
        fields:
          - label: "Releases"
            name: "releases"
            widget: "list"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
                pattern: ["^.{1,63}$", "Must be between 1 and 63 characters"]
                required: true
              - { label: "Image", name: "image", widget: "image" }
              - label: "Spotify"
                name: "spotify"
                widget: "string"
                required: false
              - label: "Apple"
                name: "apple"
                widget: "string"
                required: false
              - label: "Tidal"
                name: "tidal"
                widget: "string"
                required: false
              - label: "Amazon"
                name: "amazon"
                widget: "string"
                required: false
              - label: "Bandcamp"
                name: "bandcamp"
                widget: "string"
                required: false
              - label: "Youtube"
                name: "youtube"
                widget: "string"
                required: false
              - label: "Deezer"
                name: "deezer"
                widget: "string"
                required: false
              - label: "Image"
                name: "image"
                widget: "image"
                required: true
              - label: "Display on Music page?"
                name: "displayOnMusicPage"
                widget: "select"
                required: true
                options: ["yes", "no"]
              - label: "Presave"
                name: presave
                widget: string
                required: false
      - label: "Menu Links"
        name: "menulinks"
        file: "content/menulinks.md"
        fields:
          - { label: "Shop", name: "shop", widget: "string" }
          - { label: "Instagram", name: "instagram", widget: "string" }
          - { label: "Facebook", name: "facebook", widget: "string" }
          - { label: "X", name: "x", widget: "string" }
          - { label: "YouTube", name: "youtube", widget: "string" }
          - { label: "Spotify", name: "spotify", widget: "string" }
          - { label: "Apple", name: "apple", widget: "string" }
