backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/images
public_folder: /images
publish_mode: editorial_workflow

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Cats"
            name: "cats"
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
      - label: "Bio"
        name: "bio"
        file: "content/bio.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Watch"
        name: "watch"
        file: "content/watch.md"
        fields:
          - label: "Youtube URLs"
            name: "youtubeurls"
            widget: list
            fields:
              - { label: "URL", name: "url", widget: "string" }
