backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/images
public_folder: /images
publish_mode: editorial_workflow

collections:
  - name: "pages"
    label: "Pages"
    description: "Hi Joe"
    files:
      - label: "Bio"
        name: "bio"
        file: "content/bio.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Watch"
        name: "watch"
        file: "content/watch.md"
        fields:
          - label: "Youtube URLs"
            name: "youtubeurls"
            widget: list
            fields:
              - { label: "URL", name: "url", widget: "string" }
      - label: "Listen"
        name: "listen"
        file: "content/listen.md"
        fields:
          - label: "Releases"
            name: "releases"
            widget: "list"
            fields:
              - {
                  label: "Title",
                  name: "title",
                  widget: "string",
                  pattern: ["^.{1,63}$", "Must be between 1 and 63 characters"],
                }
              - { label: "URL", name: "url", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }
